export interface hourlyData {
  timezone: string;
  state_code: string;
  country_code: string;
  lat: number;
  lon: number;
  city_name: string;
  station_id: string;
  data: {
    rh: number;
    wind_spd: number;
    timestamp_utc: string;
    pod: string;
    slp: number;
    app_temp: number;
    elev_angle: number;
    solar_rad: number;
    pres: number;
    h_angle: number;
    dewpt: number;
    snow: number;
    uv: number;
    azimuth: number;
    wind_dir: number;
    weather: { icon: string; code: number; description: string };
    ghi: number;
    dhi: number;
    timestamp_local: string;
    vis: number;
    dni: number;
    datetime: string;
    temp: number;
    precip: number;
    clouds: number;
    ts: number;
  }[];
  sources: string[];
  city_id: string;
}

export interface APICallResponse {
  queryCost: number;
  latitude: number;
  longitude: number;
  resolvedAddress: string;
  address: string;
  timezone: string;
  tzoffset: number;
  days: WeatherDataForDay[];
  stations: Record<string, Station>;
}

export interface WeatherData {
  datetime: string;
  datetimeEpoch: number;
  temp: number;
  feelslike: number;
  humidity: number;
  dew: number;
  precip: number | null;
  precipprob: number | null;
  snow: number | null;
  snowdepth: number | null;
  preciptype: string | null;
  windgust: number | null;
  windspeed: number | null;
  winddir: number | null;
  pressure: number;
  visibility: number;
  cloudcover: number | null;
  solarradiation: number | null;
  solarenergy: number | null;
  uvindex: number;
  conditions: string;
  icon: string;
  stations: string[];
  source: string;
}

export interface WeatherDataForDay extends WeatherData {
  tempmax: number;
  tempmin: number;
  feelslikemax: number;
  feelslikemin: number;
  precipcover: number;
  snow: null;
  snowdepth: null;
  sunrise: string;
  sunriseEpoch: number;
  sunset: string;
  sunsetEpoch: number;
  moonphase: 0.43;
  description: string;
  stations: string[];
  hours: WeatherDataForHour[];
}

export type WeatherDataForHour = WeatherData;

export interface Station {
  distance: number;
  latitude: number;
  longitude: number;
  useCount: number;
  id: string;
  name: string;
  quality: number;
  contribution: number;
}

export const stub: APICallResponse = {
  queryCost: 24,
  latitude: 45.7592,
  longitude: 4.82966,
  resolvedAddress: "Lyon, Auvergne-Rhône-Alpes, France",
  address: "Lyon",
  timezone: "Europe/Paris",
  tzoffset: 2.0,
  days: [
    {
      datetime: "2021-09-17",
      datetimeEpoch: 1631829600,
      tempmax: 24.6,
      tempmin: 15.2,
      temp: 19.2,
      feelslikemax: 24.6,
      feelslikemin: 15.2,
      feelslike: 19.2,
      dew: 14.6,
      humidity: 76.35,
      precip: 0.0,
      precipprob: null,
      precipcover: 0.0,
      preciptype: null,
      snow: null,
      snowdepth: null,
      windgust: 18.4,
      windspeed: 13.1,
      winddir: 253.0,
      pressure: 1015.1,
      cloudcover: 70.6,
      visibility: 10.2,
      solarradiation: 390.9,
      solarenergy: 18.3,
      uvindex: 9.0,
      sunrise: "07:21:28",
      sunriseEpoch: 1631856088,
      sunset: "19:48:01",
      sunsetEpoch: 1631900881,
      moonphase: 0.43,
      conditions: "Partially cloudy",
      description: "Partly cloudy throughout the day.",
      icon: "partly-cloudy-day",
      stations: [
        "LFLS",
        "LFLY",
        "LFMH",
        "07481099999",
        "LFLL",
        "D2904",
        "07482099999",
        "07385099999",
      ],
      source: "obs",
      hours: [
        {
          datetime: "00:00:00",
          datetimeEpoch: 1631829600,
          temp: 17.9,
          feelslike: 17.9,
          humidity: 88.41,
          dew: 15.9,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 3.6,
          winddir: 283.0,
          pressure: 1017.1,
          visibility: 10.0,
          cloudcover: 59.4,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "01:00:00",
          datetimeEpoch: 1631833200,
          temp: 17.7,
          feelslike: 17.7,
          humidity: 89.74,
          dew: 16.0,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 11.8,
          winddir: 327.0,
          pressure: 1017.0,
          visibility: 10.0,
          cloudcover: 90.6,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "02:00:00",
          datetimeEpoch: 1631836800,
          temp: 17.7,
          feelslike: 17.7,
          humidity: 89.61,
          dew: 16.0,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 4.9,
          winddir: 341.0,
          pressure: 1017.0,
          visibility: 10.0,
          cloudcover: 89.1,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "03:00:00",
          datetimeEpoch: 1631840400,
          temp: 16.7,
          feelslike: 16.7,
          humidity: 90.65,
          dew: 15.2,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 5.9,
          winddir: 314.0,
          pressure: 1017.0,
          visibility: 10.0,
          cloudcover: 90.6,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "04:00:00",
          datetimeEpoch: 1631844000,
          temp: 16.7,
          feelslike: 16.7,
          humidity: 90.65,
          dew: 15.2,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 2.6,
          winddir: 266.0,
          pressure: 1016.1,
          visibility: 10.0,
          cloudcover: 90.6,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "05:00:00",
          datetimeEpoch: 1631847600,
          temp: 16.7,
          feelslike: 16.7,
          humidity: 85.48,
          dew: 14.3,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 5.3,
          winddir: 337.0,
          pressure: 1016.0,
          visibility: 10.0,
          cloudcover: 90.6,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "06:00:00",
          datetimeEpoch: 1631851200,
          temp: 15.2,
          feelslike: 15.2,
          humidity: 95.06,
          dew: 14.4,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 5.8,
          winddir: 339.0,
          pressure: 1016.0,
          visibility: 10.0,
          cloudcover: 90.6,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "07:00:00",
          datetimeEpoch: 1631854800,
          temp: 15.9,
          feelslike: 15.9,
          humidity: 89.41,
          dew: 14.2,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 5.9,
          winddir: 353.0,
          pressure: 1016.0,
          visibility: 10.0,
          cloudcover: 98.3,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "08:00:00",
          datetimeEpoch: 1631858400,
          temp: 15.2,
          feelslike: 15.2,
          humidity: 93.96,
          dew: 14.2,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: null,
          winddir: null,
          pressure: 1016.0,
          visibility: 9.8,
          cloudcover: 90.8,
          solarradiation: 23.0,
          solarenergy: 0.1,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "09:00:00",
          datetimeEpoch: 1631862000,
          temp: 15.7,
          feelslike: 15.7,
          humidity: 89.73,
          dew: 14.1,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 6.5,
          winddir: 331.0,
          pressure: 1016.0,
          visibility: 9.7,
          cloudcover: 90.8,
          solarradiation: 69.0,
          solarenergy: 0.2,
          uvindex: 1.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "10:00:00",
          datetimeEpoch: 1631865600,
          temp: 16.0,
          feelslike: 16.0,
          humidity: 89.28,
          dew: 14.2,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 7.0,
          winddir: 347.0,
          pressure: 1016.0,
          visibility: 10.0,
          cloudcover: 100.0,
          solarradiation: 213.0,
          solarenergy: 0.8,
          uvindex: 2.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "11:00:00",
          datetimeEpoch: 1631869200,
          temp: 18.5,
          feelslike: 18.5,
          humidity: 79.77,
          dew: 15.0,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: null,
          winddir: null,
          pressure: 1016.0,
          visibility: 10.0,
          cloudcover: 97.3,
          solarradiation: 517.0,
          solarenergy: 1.9,
          uvindex: 5.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "12:00:00",
          datetimeEpoch: 1631872800,
          temp: 20.3,
          feelslike: 20.3,
          humidity: 74.91,
          dew: 15.7,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 9.0,
          winddir: 10.0,
          pressure: 1015.3,
          visibility: 10.0,
          cloudcover: 33.9,
          solarradiation: 636.0,
          solarenergy: 2.3,
          uvindex: 6.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "13:00:00",
          datetimeEpoch: 1631876400,
          temp: 21.6,
          feelslike: 21.6,
          humidity: 66.13,
          dew: 15.0,
          precip: 0.0,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: 18.4,
          windspeed: 9.9,
          winddir: 359.0,
          pressure: 1015.0,
          visibility: 14.7,
          cloudcover: 54.8,
          solarradiation: 884.0,
          solarenergy: 3.2,
          uvindex: 9.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "07481099999", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "14:00:00",
          datetimeEpoch: 1631880000,
          temp: 23.4,
          feelslike: 23.4,
          humidity: 58.1,
          dew: 14.7,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: null,
          winddir: null,
          pressure: 1014.3,
          visibility: 10.0,
          cloudcover: 33.6,
          solarradiation: 728.0,
          solarenergy: 2.6,
          uvindex: 7.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "15:00:00",
          datetimeEpoch: 1631883600,
          temp: 23.6,
          feelslike: 23.6,
          humidity: 57.39,
          dew: 14.7,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 10.7,
          winddir: 317.0,
          pressure: 1014.0,
          visibility: 10.0,
          cloudcover: 27.2,
          solarradiation: 663.0,
          solarenergy: 2.4,
          uvindex: 7.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "16:00:00",
          datetimeEpoch: 1631887200,
          temp: 24.6,
          feelslike: 24.6,
          humidity: 53.82,
          dew: 14.7,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 8.4,
          winddir: 5.0,
          pressure: 1013.3,
          visibility: 10.0,
          cloudcover: 31.5,
          solarradiation: 552.0,
          solarenergy: 2.0,
          uvindex: 6.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "17:00:00",
          datetimeEpoch: 1631890800,
          temp: 24.5,
          feelslike: 24.5,
          humidity: 51.98,
          dew: 14.0,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 10.7,
          winddir: 347.0,
          pressure: 1013.0,
          visibility: 10.0,
          cloudcover: 30.6,
          solarradiation: 439.0,
          solarenergy: 1.6,
          uvindex: 4.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "18:00:00",
          datetimeEpoch: 1631894400,
          temp: 23.7,
          feelslike: 23.7,
          humidity: 53.61,
          dew: 13.7,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 11.1,
          winddir: 9.0,
          pressure: 1013.0,
          visibility: 10.0,
          cloudcover: 25.0,
          solarradiation: 283.0,
          solarenergy: 1.0,
          uvindex: 3.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "19:00:00",
          datetimeEpoch: 1631898000,
          temp: 22.7,
          feelslike: 22.7,
          humidity: 57.12,
          dew: 13.7,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 13.1,
          winddir: 16.0,
          pressure: 1013.0,
          visibility: 10.0,
          cloudcover: null,
          solarradiation: 56.0,
          solarenergy: 0.2,
          uvindex: 1.0,
          conditions: "Clear",
          icon: "clear-day",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "20:00:00",
          datetimeEpoch: 1631901600,
          temp: 20.9,
          feelslike: 20.9,
          humidity: 64.55,
          dew: 14.0,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 10.2,
          winddir: 26.0,
          pressure: 1013.0,
          visibility: 10.0,
          cloudcover: 100.0,
          solarradiation: 19.0,
          solarenergy: 0.1,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "D2904"],
          source: "obs",
        },
        {
          datetime: "21:00:00",
          datetimeEpoch: 1631905200,
          temp: 19.5,
          feelslike: 19.5,
          humidity: 69.97,
          dew: 13.9,
          precip: 0.0,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: 9.4,
          windspeed: 7.3,
          winddir: 356.0,
          pressure: 1013.3,
          visibility: 10.4,
          cloudcover: 47.7,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "07482099999"],
          source: "obs",
        },
        {
          datetime: "22:00:00",
          datetimeEpoch: 1631908800,
          temp: 18.7,
          feelslike: 18.7,
          humidity: 74.16,
          dew: 14.0,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: null,
          windspeed: 6.3,
          winddir: 339.0,
          pressure: 1014.0,
          visibility: 10.0,
          cloudcover: 100.0,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Overcast",
          icon: "cloudy",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL"],
          source: "obs",
        },
        {
          datetime: "23:00:00",
          datetimeEpoch: 1631912400,
          temp: 17.6,
          feelslike: 17.6,
          humidity: 79.01,
          dew: 13.9,
          precip: null,
          precipprob: null,
          snow: null,
          snowdepth: null,
          preciptype: null,
          windgust: 14.8,
          windspeed: 8.9,
          winddir: 290.0,
          pressure: 1014.0,
          visibility: 10.2,
          cloudcover: 60.3,
          solarradiation: null,
          solarenergy: null,
          uvindex: 0.0,
          conditions: "Partially cloudy",
          icon: "partly-cloudy-night",
          stations: ["LFLS", "LFLY", "LFMH", "LFLL", "07385099999"],
          source: "obs",
        },
      ],
    },
  ],
  stations: {
    LFLS: {
      distance: 58289.0,
      latitude: 45.37,
      longitude: 5.33,
      useCount: 0,
      id: "LFLS",
      name: "LFLS",
      quality: 50,
      contribution: 0.0,
    },
    LFLY: {
      distance: 10318.0,
      latitude: 45.72,
      longitude: 4.95,
      useCount: 0,
      id: "LFLY",
      name: "LFLY",
      quality: 50,
      contribution: 0.0,
    },
    LFMH: {
      distance: 48478.0,
      latitude: 45.53,
      longitude: 4.3,
      useCount: 0,
      id: "LFMH",
      name: "LFMH",
      quality: 50,
      contribution: 0.0,
    },
    "07481099999": {
      distance: 20616.0,
      latitude: 45.726,
      longitude: 5.091,
      useCount: 0,
      id: "07481099999",
      name: "SAINT EXUPERY, FR",
      quality: 100,
      contribution: 0.0,
    },
    LFLL: {
      distance: 19717.0,
      latitude: 45.73,
      longitude: 5.08,
      useCount: 0,
      id: "LFLL",
      name: "LFLL",
      quality: 49,
      contribution: 0.0,
    },
    D2904: {
      distance: 19271.0,
      latitude: 45.817,
      longitude: 4.596,
      useCount: 0,
      id: "D2904",
      name: "DW2904 Sain Bel FR",
      quality: 0,
      contribution: 0.0,
    },
    "07482099999": {
      distance: 46252.0,
      latitude: 45.987,
      longitude: 5.328,
      useCount: 0,
      id: "07482099999",
      name: "AMBERIEU, FR",
      quality: 100,
      contribution: 0.0,
    },
    "07385099999": {
      distance: 59714.0,
      latitude: 46.295,
      longitude: 4.796,
      useCount: 0,
      id: "07385099999",
      name: "CHARNAY, FR",
      quality: 100,
      contribution: 0.0,
    },
  },
};
